export default function Head() {
  return (
    <>
      <title>Ecommerce</title>
      <meta content="width=device-width, initial-scale=1" name="Market haha" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://seeklogo.com/images/S/Spider_Sport-logo-72ED0277F5-seeklogo.com.png" />
    </>
  )
}
